### ISSUE TITLE
A false positive about copies of literals

### ISSUE THREAD

**Issue by artem-anisimov-0x7f** [karamaru-alpha/copyloopvar#12] opened 2024-03-28 13:56 UTC
The following code triggers a linter warning "The copy of the 'for' variable "false" can be deleted" even though `false` is not a variable:
```
package main

func main() {
        xs := []int{0}
        ys := []int{0, 1, 2}

        for _ = range xs {
                found := false
                for _, y := range ys {
                        if y == 42 {
                                found = true
                                break
                        }
                }
                if !found {
                        continue
                }

                println("found!")
        }
}
```

**Comment by karamaru-alpha** [comment] 2024-03-28 17:39
Thank you for the report.
The issue has been resolved.

duplicate of https://github.com/karamaru-alpha/copyloopvar/issues/10

**Closed as completed by karamaru-alpha** 2024-03-28 17:39 UTC
Labels: duplicate
